version: "3.9"

services:
  # 1. База данных PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: newsbot_postgres
    env_file: .env
    # Переменные POSTGRES_DB, USER, PASSWORD подтянутся из .env автоматически
    ports:
      - "5433:5432" # 5433 для внешнего подключения
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # Используем $$, чтобы Docker не воспринимал это как переменную Compose
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - newsbot_network

  # 2. Redis (Брокер для Celery)
  redis:
    image: redis:7-alpine
    container_name: newsbot_redis
    networks:
      - newsbot_network

  # 3. ML Микросервис (Суммаризация)
#  ml-service:
#    build:
#      context: ./ml_service
#      dockerfile: Dockerfile
#    container_name: newsbot_ml_service
#    env_file: .env
#    networks:
#      - newsbot_network
#    healthcheck:
#      test: [ "CMD-SHELL", "curl -f http://localhost:8100/health || exit 1" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 20s

  # 4. Основной API (FastAPI)
  api:
    build:
      context: ./news_bot_backend
      dockerfile: Dockerfile
    container_name: newsbot_api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./news_bot_backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
#      ml-service:
#        condition: service_healthy
    networks:
      - newsbot_network
    command: >
      sh -c "
        echo 'Applying database migrations...' &&
        alembic upgrade head &&
        echo 'Starting FastAPI server...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  # 5. Celery Worker (Парсинг и логика)
  worker:
    build:
      context: ./news_bot_backend
      dockerfile: Dockerfile
    container_name: newsbot_worker
    env_file: .env
    volumes:
      - ./news_bot_backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
#      ml-service:
#        condition: service_healthy
    networks:
      - newsbot_network
    command: celery -A app.celery_app:celery_app worker --loglevel=info

  # 6. Celery Beat (Планировщик - каждые 30 минут)
  beat:
    build:
      context: ./news_bot_backend
      dockerfile: Dockerfile
    container_name: newsbot_beat
    env_file: .env
    volumes:
      - ./news_bot_backend:/app
    depends_on:
      redis:
        condition: service_started
    networks:
      - newsbot_network
    command: celery -A app.celery_app:celery_app beat --loglevel=info --pidfile=

volumes:
  postgres_data:

networks:
  newsbot_network:
    driver: bridge