version: "3.9"

services:
  redis:
    image: redis:7
    container_name: newsbot_redis
    ports:
      - "6379:6379"
    networks:
      - newsbot_network

  postgres:
    image: postgres:16-alpine
    container_name: newsbot_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - newsbot_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsbot_api
    environment:
      APP_NAME: ${APP_NAME}
      VERSION: ${VERSION}
      ENVIRONMENT: ${ENVIRONMENT}
      DEBUG: ${DEBUG}
      API_PREFIX: ${API_PREFIX}

      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      ALGORITHM: ${ALGORITHM}
      ML_SERVICE_URL: ${ML_SERVICE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      INGEST_CRON: ${INGEST_CRON}

      PYTHONPATH: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - newsbot_network
    command: >
      sh -c "
              echo 'Waiting for database...' &&
              sleep 10 &&
              echo 'Running migrations...' &&
              alembic upgrade head &&
              echo 'Starting ${APP_NAME} API server...' &&
              uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
            "

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsbot_worker
    environment:
      APP_NAME: ${APP_NAME}
      VERSION: ${VERSION}
      ENVIRONMENT: ${ENVIRONMENT}
      DEBUG: ${DEBUG}
      API_PREFIX: ${API_PREFIX}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      ALGORITHM: ${ALGORITHM}
      ML_SERVICE_URL: ${ML_SERVICE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      INGEST_CRON: ${INGEST_CRON}
      PYTHONPATH: /app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - newsbot_network
    command: >
      celery -A app.celery_app:celery_app worker --loglevel=info

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsbot_beat
    environment:
      APP_NAME: ${APP_NAME}
      VERSION: ${VERSION}
      ENVIRONMENT: ${ENVIRONMENT}
      DEBUG: ${DEBUG}
      API_PREFIX: ${API_PREFIX}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      ALGORITHM: ${ALGORITHM}
      ML_SERVICE_URL: ${ML_SERVICE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      INGEST_CRON: ${INGEST_CRON}
      PYTHONPATH: /app
    depends_on:
      redis:
        condition: service_started
    networks:
      - newsbot_network
    command: >
      celery -A app.celery_app:celery_app beat --loglevel=info

volumes:
  postgres_data:
networks:
  newsbot_network:
    driver: bridge
